---
title: "Mountain_lake_ice_validation_GEE_data"
author: "Yang_Culpepper"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

require(tidyverse)
require(lubridate)
require(here)

# file_path <- list.files(path = here('data/remote/north_american_data_by_tile/sierra_test'))
# 
# rs_gee <- do.call(bind_rows, lapply(file_path, function(x) read_csv(file = x)))

#problem with Sierra lakes tiles 3, 7: 'Error in qr.default(t(const)): NA/NaN/Inf in foreign function call (arg 1)'

rs_gee = read_csv(here("data/remote/north_american_data_by_tile/sierra_test/modis_SierraLakes_output_Terra_Aqua_merged_tile_3.csv"))

head(rs_gee)

## remote sensing data

rs_gee = rs_gee %>%
  mutate(date = as.Date(date),
         Hylak_id = as.factor(Hylak_id),
         source = as.factor(source))

# rs_gee = rs_gee %>% 
#   mutate(date = as.Date(date),
#          Hylak_id = as.factor(Hylak_id))

# rs_gee %>%
#   filter(date >= "2014-01-01",
#          !is.na(iceModis),
#          cloudModis <= 0.1) %>%
#   ggplot(aes(x = date, y = iceModis)) +
#   geom_line(alpha = 0.2) +
#   geom_point(aes(color = cloudModis), size = 0.2) +
#   scale_color_viridis_c() +
#   facet_wrap(~Hylak_id)

```

## lake ice on off date estimate from rs_gee

```{r}
rs_gee_clean = rs_gee %>% 
  filter(!is.na(iceModis),
         !is.nan(iceModis),
         !is.infinite(iceModis))

rs_gee_clean = rs_gee_clean %>% 
  filter(cloudModis <= 0.1) %>% 
  mutate(
    water_year = if_else(month(date) >= 8, year(date), year(date) - 1)
    ) 


binomial_smooth <- function(...) {
  geom_smooth(method = "glm", method.args = list(family = "binomial"), ...)
}

require(gganimate)

# t1 = 2010
# t2 = 2020
# 
# test = rs_gee_clean %>%
#   filter(
#     water_year >= t1,
#     water_year <= t2,
#     Hylak_id %in% c('1072166')) %>%
#   mutate(sdoy = date - as.Date(paste0(water_year, "-08-01")),
#          #sdoy = date - as.Date(paste0(water_year, "-10-01")),
#          ice_cover = as.integer(iceModis >= 0.8)) %>%
#   ggplot(aes(x = sdoy, y = iceModis, group = water_year)) +
#   binomial_smooth(formula = y ~ splines::ns(x, 2), aes(color = "fitted"), se = T, alpha = 0.3) +
#   # geom_vline(data = ref_clean %>% filter(water_year >= t1, water_year <= t2, Hylak_id == "1061179"), aes(xintercept = sdoy, color =     event), lwd = 1) +
#   geom_point(alpha = 0.5, pch = 8) +
#   # scale_colour_viridis_d() +
#   scale_y_continuous(labels = scales::percent_format()) +
#   #facet_grid(Hylak_id~water_year) +
#   facet_grid(~water_year)+
#   labs(
#     x = "Number of days since 08/01",
#     y = "Lake ice coverage",
#     color = ""
#   ) +
#   theme_bw()
# 
# test
```

## extract ice phenology

```{r}
calc_crossings = function(y, h = 0.5) {
  n = length(y)
  y_shifted = y - h
  crossings = which(y_shifted[1:(n - 1)] * y_shifted[2:n] < 0)

  if (length(crossings) == 0) {
    x_index = c(NA, NA)
    trend = NA
  } else {
    x_index = crossings
    trend = diff(y)[crossings]
  }

  return(list(x_index, trend))
}

pdates = rs_gee_clean %>% 
  mutate(sdoy = as.integer(date - as.Date(paste0(water_year, "-08-01")))) %>%
  group_by(Hylak_id, water_year) %>% 
  do({
    dat = .
    fit = glm(iceModis~splines::ns(sdoy, df = 2), family = "binomial", data = dat)
    sdoy_range = c(min(dat$sdoy): max(dat$sdoy))
    pred = predict(fit, newdata = tibble(sdoy = sdoy_range), type = "response", se.fit = T)
    
    temp = calc_crossings(pred$fit, h = 0.5)
    crossings_index = temp[[1]]
    trend = temp[[2]] >= 0
    # crossings_plus_index = calc_crossings(pred$fit + pred$se.fit, h = 0.5)
    # crossings_minus_index = calc_crossings(pred$fit - pred$se.fit, h = 0.5)
    
    tibble(sdoy_fit = sdoy_range[crossings_index], trend = trend)
    
  }) %>% ungroup() %>% 
  distinct() %>% 
  mutate(event = factor(trend, levels = c(T, F), labels = c("ice_on", "ice_off")))

#unique(pdates$Hylak_id)

write_csv(pdates, here('data/n_american_ice_phenology/sierra_lakes_tile_3.csv'))


# pdates %>% 
#   ggplot +
#   geom_point(aes(x = water_year, y = sdoy_fit), color = "black") +
#   geom_point(data = ref_clean, aes(x = water_year, y = sdoy, color = event)) +
#   facet_wrap(~Hylak_id) +
#   theme_bw()

# merged_pdates = pdates %>% 
#   inner_join(ref_clean, by = c("Hylak_id", "water_year", "event")) %>% 
#   mutate(date_modis = as.Date(paste0(water_year, "-08-01")) + sdoy_fit)
#   #mutate(date_modis = as.Date(paste0(water_year, "-10-01")) + sdoy_fit)

#write_csv(merged_pdates, here('data/combined/merged_pdates.csv'))

# merged_pdates %>% 
#   mutate(dif = sdoy_fit - as.numeric(sdoy)) %>%
#   group_by(Hylak_id, event) %>% 
#   #group_by(event) %>%
#   summarise(
#     MBS = mean(dif),
#     MAE = mean(abs(dif)),
#     RMSE = sqrt(mean(dif^2)),
#     N = n()) %>% 
#   ungroup() %>% 
#   arrange(event, MAE)
#write_csv(error, here('data/combined/error_pdates_2022.04.18.csv'))

# merged_pdates %>% 
#   ggplot(aes(x = sdoy_fit, y = sdoy)) + #, pch = Hylak_id
#   geom_point() +
#   geom_abline(aes(slope = 1, intercept = 0, color = "1:1 line")) +
#   #facet_grid(Hylak_id~event, scales = "free") +
#   facet_grid(~event, scales = "free") +
#   theme_bw() +
#   labs(x = "Days since 8/1 from MODIS",
#        y = "Days since 8/1 from in situ",
#        color = "Lake name" #,
#        ) #pch = "Lake name"
# 
# validation = merged_pdates %>% 
#   ggplot(aes(x = sdoy_fit, y = sdoy, color = Hylak_id)) + #pch = Hylak_id, 
#   geom_point() +
#   geom_abline(aes(slope = 1, intercept = 0), color = "black") +
#   facet_wrap(~event, scales = "free") +
#   theme_bw() +
#   labs(x = "Days since 8/1 from MODIS",
#        y = "Days since 8/1 from in situ",
#        color = "Lake name",
#        pch = "Lake name")

################################################################################
#Idea: Plot with all grey points for all lakes and then a plot with black points for "suitable" lakes, so we can see the contrast.

```

